const phrasesDB = [
  // ==========================================
  // ТЕМА 1: BASICS (Основы и Приветствия)
  // ==========================================
  {
    id: 1,
    topic: "basics",
    de: "Hallo",
    ru: "Привет",
    grammar: "Универсальное приветствие.",
  },
  {
    id: 2,
    topic: "basics",
    de: "Guten Morgen",
    ru: "Доброе утро",
    grammar: "Используется до 11:00.",
  },
  {
    id: 3,
    topic: "basics",
    de: "Guten Tag",
    ru: "Добрый день",
    grammar: "Основное приветствие (11:00-18:00).",
  },
  {
    id: 4,
    topic: "basics",
    de: "Guten Abend",
    ru: "Добрый вечер",
    grammar: "После 18:00.",
  },
  {
    id: 5,
    topic: "basics",
    de: "Gute Nacht",
    ru: "Спокойной ночи",
    grammar: "Только при прощании перед сном.",
  },
  {
    id: 6,
    topic: "basics",
    de: "Tschüss",
    ru: "Пока",
    grammar: "Неформальное прощание.",
  },
  {
    id: 7,
    topic: "basics",
    de: "Auf Wiedersehen",
    ru: "До свидания",
    grammar: "Формальное прощание.",
  },
  {
    id: 8,
    topic: "basics",
    de: "Wie geht es Ihnen?",
    ru: "Как у Вас дела?",
    grammar: "Ihnen (Вам) — Dativ.",
  },
  {
    id: 9,
    topic: "basics",
    de: "Mir geht es gut",
    ru: "У меня всё хорошо",
    grammar: "Mir (мне) — Dativ.",
  },
  {
    id: 10,
    topic: "basics",
    de: "Wie heißen Sie?",
    ru: "Как Вас зовут?",
    grammar: "Sie с большой буквы — Вы.",
  },
  {
    id: 11,
    topic: "basics",
    de: "Ich heiße Alex",
    ru: "Меня зовут Алекс",
    grammar: "Глагол heißen.",
  },
  {
    id: 12,
    topic: "basics",
    de: "Freut mich",
    ru: "Приятно познакомиться",
    grammar: "Короткая форма.",
  },
  {
    id: 13,
    topic: "basics",
    de: "Woher kommen Sie?",
    ru: "Откуда Вы?",
    grammar: "Глагол kommen + aus.",
  },
  {
    id: 14,
    topic: "basics",
    de: "Ich komme aus Deutschland",
    ru: "Я из Германии",
    grammar: "Предлог aus требует Dativ.",
  },
  {
    id: 15,
    topic: "basics",
    de: "Ich wohne in Berlin",
    ru: "Я живу в Берлине",
    grammar: "Предлог in + Город.",
  },
  {
    id: 16,
    topic: "basics",
    de: "Sprechen Sie Deutsch?",
    ru: "Вы говорите по-немецки?",
    grammar: "Сильный глагол sprechen (e -> i).",
  },
  {
    id: 17,
    topic: "basics",
    de: "Ich spreche kein Deutsch",
    ru: "Я не говорю по-немецки",
    grammar: "Kein — отрицание существительного.",
  },
  {
    id: 18,
    topic: "basics",
    de: "Entschuldigung",
    ru: "Извините",
    grammar: "Для привлечения внимания.",
  },
  {
    id: 19,
    topic: "basics",
    de: "Es tut mir leid",
    ru: "Мне жаль",
    grammar: "Выражение сожаления.",
  },
  {
    id: 20,
    topic: "basics",
    de: "Vielen Dank",
    ru: "Большое спасибо",
    grammar: "Усиленная благодарность.",
  },
  {
    id: 21,
    topic: "basics",
    de: "Bitte schön",
    ru: "Пожалуйста",
    grammar: "Ответ на спасибо.",
  },
  {
    id: 22,
    topic: "basics",
    de: "Ja / Nein",
    ru: "Да / Нет",
    grammar: "Базовые ответы.",
  },
  {
    id: 23,
    topic: "basics",
    de: "Vielleicht",
    ru: "Может быть",
    grammar: "Наречие.",
  },
  {
    id: 24,
    topic: "basics",
    de: "Kein Problem",
    ru: "Без проблем",
    grammar: "Kein для среднего рода.",
  },
  {
    id: 25,
    topic: "basics",
    de: "Ich verstehe nicht",
    ru: "Я не понимаю",
    grammar: "Отрицание глагола — nicht.",
  },

  // ==========================================
  // ТЕМА 2: GRAMMAR (Глаголы, Падежи, Структура)
  // ==========================================
  // Nominativ & Sein
  {
    id: 26,
    topic: "grammar",
    de: "Ich bin müde",
    ru: "Я устал",
    grammar: "Глагол sein (bin).",
  },
  {
    id: 27,
    topic: "grammar",
    de: "Er ist Lehrer",
    ru: "Он учитель",
    grammar: "Профессии без артикля.",
  },
  {
    id: 28,
    topic: "grammar",
    de: "Wir sind Freunde",
    ru: "Мы друзья",
    grammar: "Plural.",
  },
  {
    id: 29,
    topic: "grammar",
    de: "Das ist ein Tisch",
    ru: "Это стол",
    grammar: "Ein — неопределенный артикль (Nom).",
  },

  // Akkusativ (Кого? Что?)
  {
    id: 30,
    topic: "grammar",
    de: "Ich habe einen Bruder",
    ru: "У меня есть брат",
    grammar: "Haben + Akkusativ (der -> einen).",
  },
  {
    id: 31,
    topic: "grammar",
    de: "Ich esse einen Apfel",
    ru: "Я ем яблоко",
    grammar: "Essen + Akkusativ.",
  },
  {
    id: 32,
    topic: "grammar",
    de: "Ich suche den Bahnhof",
    ru: "Я ищу вокзал",
    grammar: "Suchen + Akkusativ.",
  },
  {
    id: 33,
    topic: "grammar",
    de: "Wir kaufen ein Auto",
    ru: "Мы покупаем машину",
    grammar: "Das Auto (ср.род) не меняется.",
  },
  {
    id: 34,
    topic: "grammar",
    de: "Ich liebe dich",
    ru: "Я тебя люблю",
    grammar: "Dich — тебя (Akkusativ).",
  },
  {
    id: 35,
    topic: "grammar",
    de: "Ich rufe dich an",
    ru: "Я тебе позвоню",
    grammar: "Глагол anrufen (с отделяемой приставкой).",
  },
  {
    id: 36,
    topic: "grammar",
    de: "Sie liest ein Buch",
    ru: "Она читает книгу",
    grammar: "Сильный глагол (ie).",
  },
  {
    id: 37,
    topic: "grammar",
    de: "Möchten Sie einen Tee?",
    ru: "Хотите чай?",
    grammar: "Вежливая форма.",
  },

  // Dativ (Кому? Где?)
  {
    id: 38,
    topic: "grammar",
    de: "Ich helfe dem Mann",
    ru: "Я помогаю мужчине",
    grammar: "Helfen + Dativ (der -> dem).",
  },
  {
    id: 39,
    topic: "grammar",
    de: "Wie geht es dir?",
    ru: "Как у тебя дела?",
    grammar: "Dir — тебе (Dativ).",
  },
  {
    id: 40,
    topic: "grammar",
    de: "Das gehört mir",
    ru: "Это принадлежит мне",
    grammar: "Gehören + Dativ.",
  },
  {
    id: 41,
    topic: "grammar",
    de: "Ich fahre mit dem Bus",
    ru: "Я еду на автобусе",
    grammar: "Mit всегда + Dativ.",
  },
  {
    id: 42,
    topic: "grammar",
    de: "Ich wohne bei meinen Eltern",
    ru: "Я живу у родителей",
    grammar: "Bei всегда + Dativ.",
  },
  {
    id: 43,
    topic: "grammar",
    de: "Nach der Arbeit",
    ru: "После работы",
    grammar: "Nach всегда + Dativ.",
  },

  // Modalverben (Модальные глаголы)
  {
    id: 44,
    topic: "grammar",
    de: "Ich kann schwimmen",
    ru: "Я умею плавать",
    grammar: "Können (мочь/уметь).",
  },
  {
    id: 45,
    topic: "grammar",
    de: "Ich muss arbeiten",
    ru: "Я должен работать",
    grammar: "Müssen (обязанность).",
  },
  {
    id: 46,
    topic: "grammar",
    de: "Wir wollen reisen",
    ru: "Мы хотим путешествовать",
    grammar: "Wollen (желание).",
  },
  {
    id: 47,
    topic: "grammar",
    de: "Darf ich hier rauchen?",
    ru: "Можно мне здесь курить?",
    grammar: "Dürfen (разрешение).",
  },
  {
    id: 48,
    topic: "grammar",
    de: "Du sollst schlafen",
    ru: "Тебе следует спать",
    grammar: "Sollen (совет).",
  },
  {
    id: 49,
    topic: "grammar",
    de: "Ich möchte bezahlen",
    ru: "Я хотел бы заплатить",
    grammar: "Möchte (вежливое желание).",
  },

  // Perfekt (Прошедшее время)
  {
    id: 50,
    topic: "grammar",
    de: "Ich habe gemacht",
    ru: "Я сделал",
    grammar: "Haben + Ge...t (Слабый глагол).",
  },
  {
    id: 51,
    topic: "grammar",
    de: "Ich habe gelernt",
    ru: "Я учил",
    grammar: "Haben + Ge...t.",
  },
  {
    id: 52,
    topic: "grammar",
    de: "Ich habe gegessen",
    ru: "Я поел",
    grammar: "Сильный глагол (ge-gessen).",
  },
  {
    id: 53,
    topic: "grammar",
    de: "Ich habe getrunken",
    ru: "Я попил",
    grammar: "Сильный глагол (ge-trunken).",
  },
  {
    id: 54,
    topic: "grammar",
    de: "Er hat geschrieben",
    ru: "Он написал",
    grammar: "Сильный глагол (ge-schrieben).",
  },
  {
    id: 55,
    topic: "grammar",
    de: "Wir haben gesehen",
    ru: "Мы видели",
    grammar: "Сильный глагол (ge-sehen).",
  },
  {
    id: 56,
    topic: "grammar",
    de: "Ich bin gegangen",
    ru: "Я пошел",
    grammar: "Sein + Движение.",
  },
  {
    id: 57,
    topic: "grammar",
    de: "Er ist gefahren",
    ru: "Он поехал",
    grammar: "Sein + Движение.",
  },
  {
    id: 58,
    topic: "grammar",
    de: "Sie ist gekommen",
    ru: "Она пришла",
    grammar: "Sein + Движение.",
  },
  {
    id: 59,
    topic: "grammar",
    de: "Ich bin aufgestanden",
    ru: "Я встал (проснулся)",
    grammar: "Sein + Изменение состояния.",
  },
  {
    id: 60,
    topic: "grammar",
    de: "Was ist passiert?",
    ru: "Что случилось?",
    grammar: "Sein + Passieren.",
  },

  // ==========================================
  // ТЕМА 3: FOOD (Еда и Ресторан)
  // ==========================================
  {
    id: 61,
    topic: "food",
    de: "Ich habe Hunger",
    ru: "Я голоден",
    grammar: "Дословно: Имею голод.",
  },
  {
    id: 62,
    topic: "food",
    de: "Ich habe Durst",
    ru: "Я хочу пить",
    grammar: "Дословно: Имею жажду.",
  },
  {
    id: 63,
    topic: "food",
    de: "Die Speisekarte, bitte",
    ru: "Меню, пожалуйста",
    grammar: "Существительное Feminin.",
  },
  {
    id: 64,
    topic: "food",
    de: "Ich nehme eine Pizza",
    ru: "Я возьму пиццу",
    grammar: "Nehmen + Akkusativ.",
  },
  {
    id: 65,
    topic: "food",
    de: "Schmeckt es Ihnen?",
    ru: "Вам вкусно?",
    grammar: "Глагол schmecken + Dativ.",
  },
  {
    id: 66,
    topic: "food",
    de: "Das ist lecker",
    ru: "Это вкусно",
    grammar: "Прилагательное.",
  },
  {
    id: 67,
    topic: "food",
    de: "Die Rechnung, bitte",
    ru: "Счет, пожалуйста",
    grammar: "В конце еды.",
  },
  {
    id: 68,
    topic: "food",
    de: "Zusammen oder getrennt?",
    ru: "Вместе или раздельно?",
    grammar: "Вопрос официанта.",
  },
  {
    id: 69,
    topic: "food",
    de: "Guten Appetit",
    ru: "Приятного аппетита",
    grammar: "Пожелание.",
  },
  {
    id: 70,
    topic: "food",
    de: "Ich esse kein Fleisch",
    ru: "Я не ем мясо",
    grammar: "Kein перед существительным.",
  },
  {
    id: 71,
    topic: "food",
    de: "Ein Bier, bitte",
    ru: "Одно пиво, пожалуйста",
    grammar: "Заказ напитка.",
  },
  {
    id: 72,
    topic: "food",
    de: "Frühstück",
    ru: "Завтрак",
    grammar: "Средний род.",
  },
  {
    id: 73,
    topic: "food",
    de: "Mittagessen",
    ru: "Обед",
    grammar: "Средний род.",
  },
  {
    id: 74,
    topic: "food",
    de: "Abendessen",
    ru: "Ужин",
    grammar: "Средний род.",
  },
  {
    id: 75,
    topic: "food",
    de: "Das Wasser",
    ru: "Вода",
    grammar: "Средний род.",
  },

  // ==========================================
  // ТЕМА 4: CITY (Город, Транспорт, Ориентация)
  // ==========================================
  {
    id: 76,
    topic: "city",
    de: "Wo ist der Bahnhof?",
    ru: "Где вокзал?",
    grammar: "Вопрос о месте (Nominativ).",
  },
  {
    id: 77,
    topic: "city",
    de: "Entschuldigung, wo ist...?",
    ru: "Извините, где...?",
    grammar: "Вежливое начало.",
  },
  {
    id: 78,
    topic: "city",
    de: "Gehen Sie geradeaus",
    ru: "Идите прямо",
    grammar: "Imperativ (Повелительное).",
  },
  {
    id: 79,
    topic: "city",
    de: "Dann nach links",
    ru: "Потом налево",
    grammar: "Направление.",
  },
  {
    id: 80,
    topic: "city",
    de: "Dann nach rechts",
    ru: "Потом направо",
    grammar: "Направление.",
  },
  {
    id: 81,
    topic: "city",
    de: "Ist das weit?",
    ru: "Это далеко?",
    grammar: "Вопрос о расстоянии.",
  },
  {
    id: 82,
    topic: "city",
    de: "Eine Fahrkarte nach Berlin",
    ru: "Один билет в Берлин",
    grammar: "Nach + Город.",
  },
  {
    id: 83,
    topic: "city",
    de: "Der Zug hat Verspätung",
    ru: "Поезд опаздывает",
    grammar: "Существительное Verspätung.",
  },
  {
    id: 84,
    topic: "city",
    de: "Am Bahnhof",
    ru: "На вокзале",
    grammar: "An dem (Dativ).",
  },
  {
    id: 85,
    topic: "city",
    de: "Im Hotel",
    ru: "В отеле",
    grammar: "In dem (Dativ).",
  },
  {
    id: 86,
    topic: "city",
    de: "Die Apotheke",
    ru: "Аптека",
    grammar: "Женский род.",
  },
  {
    id: 87,
    topic: "city",
    de: "Das Krankenhaus",
    ru: "Больница",
    grammar: "Средний род.",
  },
  {
    id: 88,
    topic: "city",
    de: "Der Flughafen",
    ru: "Аэропорт",
    grammar: "Мужской род.",
  },
  { id: 89, topic: "city", de: "Halt!", ru: "Стой!", grammar: "Команда." },
  {
    id: 90,
    topic: "city",
    de: "Eingang / Ausgang",
    ru: "Вход / Выход",
    grammar: "Антонимы.",
  },

  // ==========================================
  // ТЕМА 5: FAMILY (Семья и Люди)
  // ==========================================
  {
    id: 91,
    topic: "family",
    de: "Das ist meine Mutter",
    ru: "Это моя мама",
    grammar: "Притяжательное (моя).",
  },
  {
    id: 92,
    topic: "family",
    de: "Das ist mein Vater",
    ru: "Это мой папа",
    grammar: "Притяжательное (мой).",
  },
  {
    id: 93,
    topic: "family",
    de: "Ich habe Geschwister",
    ru: "У меня есть братья/сестры",
    grammar: "Множественное число.",
  },
  {
    id: 94,
    topic: "family",
    de: "Ich bin verheiratet",
    ru: "Я женат/замужем",
    grammar: "Статус.",
  },
  {
    id: 95,
    topic: "family",
    de: "Ich bin ledig",
    ru: "Я холост",
    grammar: "Статус.",
  },
  {
    id: 96,
    topic: "family",
    de: "Hast du Kinder?",
    ru: "У тебя есть дети?",
    grammar: "Вопрос.",
  },
  {
    id: 97,
    topic: "family",
    de: "Meine Eltern",
    ru: "Мои родители",
    grammar: "Plural.",
  },
  {
    id: 98,
    topic: "family",
    de: "Die Oma / Der Opa",
    ru: "Бабушка / Дедушка",
    grammar: "Разговорные формы.",
  },
  {
    id: 99,
    topic: "family",
    de: "Der Freund",
    ru: "Друг",
    grammar: "Мужской род.",
  },
  {
    id: 100,
    topic: "family",
    de: "Die Freundin",
    ru: "Подруга",
    grammar: "Женский род (суффикс -in).",
  },

  // ==========================================
  // ТЕМА 6: TIME (Время и Даты)
  // ==========================================
  {
    id: 101,
    topic: "time",
    de: "Wie spät ist es?",
    ru: "Который час?",
    grammar: "Стандартный вопрос.",
  },
  {
    id: 102,
    topic: "time",
    de: "Es ist zwei Uhr",
    ru: "Сейчас два часа",
    grammar: "Официальное время.",
  },
  {
    id: 103,
    topic: "time",
    de: "Halb drei",
    ru: "Половина третьего",
    grammar: "2:30.",
  },
  {
    id: 104,
    topic: "time",
    de: "Viertel nach zwei",
    ru: "Четверть третьего (после 2)",
    grammar: "2:15.",
  },
  {
    id: 105,
    topic: "time",
    de: "Viertel vor drei",
    ru: "Без четверти три",
    grammar: "2:45.",
  },
  {
    id: 106,
    topic: "time",
    de: "Heute",
    ru: "Сегодня",
    grammar: "Наречие времени.",
  },
  {
    id: 107,
    topic: "time",
    de: "Morgen",
    ru: "Завтра",
    grammar: "Наречие времени.",
  },
  {
    id: 108,
    topic: "time",
    de: "Gestern",
    ru: "Вчера",
    grammar: "Наречие времени.",
  },
  {
    id: 109,
    topic: "time",
    de: "Am Montag",
    ru: "В понедельник",
    grammar: "Дни недели -> Am.",
  },
  {
    id: 110,
    topic: "time",
    de: "Im Sommer",
    ru: "Летом",
    grammar: "Времена года -> Im.",
  },
  {
    id: 111,
    topic: "time",
    de: "Wann?",
    ru: "Когда?",
    grammar: "Вопросительное слово.",
  },
  { id: 112, topic: "time", de: "Jetzt", ru: "Сейчас", grammar: "Наречие." },
  {
    id: 113,
    topic: "time",
    de: "Später",
    ru: "Позже",
    grammar: "Сравнительная степень.",
  },
  {
    id: 114,
    topic: "time",
    de: "Jeden Tag",
    ru: "Каждый день",
    grammar: "Akkusativ времени.",
  },
  {
    id: 115,
    topic: "time",
    de: "Das Wochenende",
    ru: "Выходные",
    grammar: "Средний род.",
  },

  // ==========================================
  // ТЕМА 7: SHOPPING (Покупки и Одежда)
  // ==========================================
  {
    id: 116,
    topic: "shopping",
    de: "Was kostet das?",
    ru: "Сколько это стоит?",
    grammar: "Вопрос о цене.",
  },
  {
    id: 117,
    topic: "shopping",
    de: "Das ist zu teuer",
    ru: "Это слишком дорого",
    grammar: "Zu = слишком.",
  },
  {
    id: 118,
    topic: "shopping",
    de: "Das ist billig",
    ru: "Это дешево",
    grammar: "Прилагательное.",
  },
  {
    id: 119,
    topic: "shopping",
    de: "Kann ich mit Karte zahlen?",
    ru: "Могу я оплатить картой?",
    grammar: "Können + Infinitiv.",
  },
  {
    id: 120,
    topic: "shopping",
    de: "Nur Bargeld",
    ru: "Только наличные",
    grammar: "Фраза кассира.",
  },
  {
    id: 121,
    topic: "shopping",
    de: "Ich schaue nur",
    ru: "Я только смотрю",
    grammar: "Ответ продавцу.",
  },
  {
    id: 122,
    topic: "shopping",
    de: "Haben Sie das in Rot?",
    ru: "У вас есть это в красном?",
    grammar: "Вопрос о цвете.",
  },
  {
    id: 123,
    topic: "shopping",
    de: "Welche Größe?",
    ru: "Какой размер?",
    grammar: "Вопросительное слово Welche.",
  },
  {
    id: 124,
    topic: "shopping",
    de: "Kann ich das anprobieren?",
    ru: "Могу я это примерить?",
    grammar: "Глагол anprobieren.",
  },
  {
    id: 125,
    topic: "shopping",
    de: "Die Tüte",
    ru: "Пакет",
    grammar: "Женский род.",
  },
  {
    id: 126,
    topic: "shopping",
    de: "Der Supermarkt",
    ru: "Супермаркет",
    grammar: "Мужской род.",
  },
  {
    id: 127,
    topic: "shopping",
    de: "Öffnungszeiten",
    ru: "Часы работы",
    grammar: "Plural.",
  },
  {
    id: 128,
    topic: "shopping",
    de: "Geschlossen",
    ru: "Закрыто",
    grammar: "Participle II как прилагательное.",
  },
  {
    id: 129,
    topic: "shopping",
    de: "Geöffnet",
    ru: "Открыто",
    grammar: "Participle II как прилагательное.",
  },

  // ==========================================
  // ТЕМА 8: HOME (Дом и Быт)
  // ==========================================
  {
    id: 130,
    topic: "home",
    de: "Meine Adresse ist...",
    ru: "Мой адрес...",
    grammar: "Притяжательное.",
  },
  {
    id: 131,
    topic: "home",
    de: "Ich suche eine Wohnung",
    ru: "Я ищу квартиру",
    grammar: "Suchen + Akkusativ.",
  },
  {
    id: 132,
    topic: "home",
    de: "Wie hoch ist die Miete?",
    ru: "Какая арендная плата?",
    grammar: "Вопрос цены.",
  },
  {
    id: 133,
    topic: "home",
    de: "Das Zimmer",
    ru: "Комната",
    grammar: "Средний род.",
  },
  {
    id: 134,
    topic: "home",
    de: "Der Schlüssel",
    ru: "Ключ",
    grammar: "Мужской род.",
  },
  {
    id: 135,
    topic: "home",
    de: "Das Fenster ist offen",
    ru: "Окно открыто",
    grammar: "Прилагательное.",
  },
  {
    id: 136,
    topic: "home",
    de: "Mach das Licht an",
    ru: "Включи свет",
    grammar: "Anmachen (включать).",
  },
  {
    id: 137,
    topic: "home",
    de: "Mach das Licht aus",
    ru: "Выключи свет",
    grammar: "Ausmachen (выключать).",
  },
  {
    id: 138,
    topic: "home",
    de: "Der Kühlschrank",
    ru: "Холодильник",
    grammar: "Мужской род.",
  },
  {
    id: 139,
    topic: "home",
    de: "Das Bad",
    ru: "Ванная",
    grammar: "Сокращение от Badezimmer.",
  },
  {
    id: 140,
    topic: "home",
    de: "Auf dem Tisch",
    ru: "На столе",
    grammar: "Auf + Dativ (Где?).",
  },
  {
    id: 141,
    topic: "home",
    de: "Im Bett",
    ru: "В кровати",
    grammar: "In + Dativ (Где?).",
  },
  {
    id: 142,
    topic: "home",
    de: "Groß / Klein",
    ru: "Большой / Маленький",
    grammar: "Антонимы.",
  },
  {
    id: 143,
    topic: "home",
    de: "Neu / Alt",
    ru: "Новый / Старый",
    grammar: "Антонимы.",
  },

  // ==========================================
  // ТЕМА 9: HEALTH (Здоровье)
  // ==========================================
  {
    id: 144,
    topic: "health",
    de: "Ich bin krank",
    ru: "Я болен",
    grammar: "Sein + Adjektiv.",
  },
  {
    id: 145,
    topic: "health",
    de: "Ich brauche einen Arzt",
    ru: "Мне нужен врач",
    grammar: "Brauchen + Akkusativ.",
  },
  {
    id: 146,
    topic: "health",
    de: "Ich habe Kopfschmerzen",
    ru: "У меня болит голова",
    grammar: "Сложное сущ. (Kopf + Schmerz).",
  },
  {
    id: 147,
    topic: "health",
    de: "Mein Bauch tut weh",
    ru: "У меня болит живот",
    grammar: "Глагол wehtun (болеть).",
  },
  {
    id: 148,
    topic: "health",
    de: "Gute Besserung",
    ru: "Выздоравливай",
    grammar: "Пожелание.",
  },
  {
    id: 149,
    topic: "health",
    de: "Ich habe Fieber",
    ru: "У меня температура",
    grammar: "Haben.",
  },
  {
    id: 150,
    topic: "health",
    de: "Der Termin",
    ru: "Прием / Встреча",
    grammar: "Запись к врачу.",
  },

  // ==========================================
  // ТЕМА 10: COMMUNICATION (Общение и Связки)
  // ==========================================
  {
    id: 151,
    topic: "communication",
    de: "Genau",
    ru: "Точно",
    grammar: "Согласие.",
  },
  {
    id: 152,
    topic: "communication",
    de: "Natürlich",
    ru: "Конечно",
    grammar: "Согласие.",
  },
  {
    id: 153,
    topic: "communication",
    de: "Einverstanden",
    ru: "Согласен / Договорились",
    grammar: "Согласие.",
  },
  {
    id: 154,
    topic: "communication",
    de: "Viel Spaß",
    ru: "Желаю повеселиться",
    grammar: "Пожелание.",
  },
  {
    id: 155,
    topic: "communication",
    de: "Viel Glück",
    ru: "Удачи",
    grammar: "Пожелание.",
  },
  {
    id: 156,
    topic: "communication",
    de: "Ich weiß nicht",
    ru: "Я не знаю",
    grammar: "Глагол wissen.",
  },
  {
    id: 157,
    topic: "communication",
    de: "Keine Ahnung",
    ru: "Без понятия",
    grammar: "Разговорная фраза.",
  },
  {
    id: 158,
    topic: "communication",
    de: "Warum?",
    ru: "Почему?",
    grammar: "Вопрос.",
  },
  {
    id: 159,
    topic: "communication",
    de: "Weil...",
    ru: "Потому что...",
    grammar: "Ответ (глагол идет в конец).",
  },
  {
    id: 160,
    topic: "communication",
    de: "Und du?",
    ru: "А ты?",
    grammar: "Встречный вопрос.",
  },
  {
    id: 161,
    topic: "communication",
    de: "Alles klar",
    ru: "Всё понятно",
    grammar: "Утверждение.",
  },
  {
    id: 162,
    topic: "communication",
    de: "Hilfe!",
    ru: "Помогите!",
    grammar: "Призыв.",
  },
  { id: 163, topic: "communication", de: "Aber", ru: "Но", grammar: "Союз." },
  { id: 164, topic: "communication", de: "Oder", ru: "Или", grammar: "Союз." },
  { id: 165, topic: "communication", de: "Und", ru: "И", grammar: "Союз." },
  {
    id: 166,
    topic: "communication",
    de: "Zum Beispiel",
    ru: "Например",
    grammar: "Вводная фраза.",
  },

  // ==========================================
  // ТЕМА 11: WORK (Работа)
  // ==========================================
  {
    id: 167,
    topic: "work",
    de: "Was sind Sie von Beruf?",
    ru: "Кто Вы по профессии?",
    grammar: "Стандартный вопрос.",
  },
  {
    id: 168,
    topic: "work",
    de: "Ich arbeite als Lehrer",
    ru: "Я работаю учителем",
    grammar: "Als + Профессия.",
  },
  {
    id: 169,
    topic: "work",
    de: "Ich bin Student",
    ru: "Я студент",
    grammar: "Без артикля.",
  },
  {
    id: 170,
    topic: "work",
    de: "Ich habe viel Arbeit",
    ru: "У меня много работы",
    grammar: "Viel (много).",
  },
  {
    id: 171,
    topic: "work",
    de: "Die Pause",
    ru: "Перерыв",
    grammar: "Женский род.",
  },
  {
    id: 172,
    topic: "work",
    de: "Der Chef",
    ru: "Начальник",
    grammar: "Мужской род.",
  },
  {
    id: 173,
    topic: "work",
    de: "Das Büro",
    ru: "Офис",
    grammar: "Средний род.",
  },
  {
    id: 174,
    topic: "work",
    de: "Arbeitslos",
    ru: "Безработный",
    grammar: "Суффикс -los (без).",
  },
  {
    id: 175,
    topic: "work",
    de: "Der Computer",
    ru: "Компьютер",
    grammar: "Мужской род.",
  },

  // ==========================================
  // ТЕМА 12: PHONE (Телефон)
  // ==========================================
  {
    id: 176,
    topic: "phone",
    de: "Meine Nummer ist...",
    ru: "Мой номер...",
    grammar: "Притяжательное.",
  },
  {
    id: 177,
    topic: "phone",
    de: "Wie ist das WLAN Passwort?",
    ru: "Какой пароль от Wi-Fi?",
    grammar: "Wie (какой) в данном контексте.",
  },
  {
    id: 178,
    topic: "phone",
    de: "Mein Akku ist leer",
    ru: "Батарея села",
    grammar: "Leer (пустой).",
  },
  {
    id: 179,
    topic: "phone",
    de: "Schreiben Sie mir",
    ru: "Напишите мне",
    grammar: "Imperativ + Dativ.",
  },
  {
    id: 180,
    topic: "phone",
    de: "Ich höre dich nicht",
    ru: "Я тебя не слышу",
    grammar: "Akkusativ.",
  },

  // ==========================================
  // ТЕМА 13: WEATHER (Погода)
  // ==========================================
  {
    id: 181,
    topic: "weather",
    de: "Wie ist das Wetter?",
    ru: "Как погода?",
    grammar: "Вопрос.",
  },
  {
    id: 182,
    topic: "weather",
    de: "Die Sonne scheint",
    ru: "Светит солнце",
    grammar: "Nominativ.",
  },
  {
    id: 183,
    topic: "weather",
    de: "Es regnet",
    ru: "Идет дождь",
    grammar: "Безличный глагол.",
  },
  {
    id: 184,
    topic: "weather",
    de: "Es schneit",
    ru: "Идет снег",
    grammar: "Безличный глагол.",
  },
  {
    id: 185,
    topic: "weather",
    de: "Es ist kalt",
    ru: "Холодно",
    grammar: "Безличное.",
  },
  {
    id: 186,
    topic: "weather",
    de: "Es ist warm",
    ru: "Тепло",
    grammar: "Безличное.",
  },
  {
    id: 187,
    topic: "weather",
    de: "Mir ist kalt",
    ru: "Мне холодно",
    grammar: "Dativ субъекта (Мне).",
  },

  // ==========================================
  // ДОПОЛНИТЕЛЬНАЯ ГРАММАТИКА (Сложные случаи)
  // ==========================================
  {
    id: 188,
    topic: "grammar",
    de: "Sei leise!",
    ru: "Будь тише!",
    grammar: "Imperativ от sein (Sei!).",
  },
  {
    id: 189,
    topic: "grammar",
    de: "Hör zu!",
    ru: "Послушай!",
    grammar: "Imperativ от zuhören.",
  },
  {
    id: 190,
    topic: "grammar",
    de: "Steh auf!",
    ru: "Вставай!",
    grammar: "Imperativ от aufstehen.",
  },
  {
    id: 191,
    topic: "grammar",
    de: "Nimm das!",
    ru: "Возьми это!",
    grammar: "Imperativ от nehmen (сильный).",
  },
  {
    id: 192,
    topic: "grammar",
    de: "Lies den Text",
    ru: "Прочитай текст",
    grammar: "Imperativ от lesen (сильный).",
  },
  {
    id: 193,
    topic: "grammar",
    de: "Ich war zu Hause",
    ru: "Я был дома",
    grammar: "Präteritum от sein (war).",
  },
  {
    id: 194,
    topic: "grammar",
    de: "Ich hatte keine Zeit",
    ru: "У меня не было времени",
    grammar: "Präteritum от haben (hatte).",
  },
  {
    id: 195,
    topic: "grammar",
    de: "Seit einem Jahr",
    ru: "Уже год",
    grammar: "Seit + Dativ (как долго?).",
  },
  {
    id: 196,
    topic: "grammar",
    de: "Für mich",
    ru: "Для меня",
    grammar: "Für + Akkusativ.",
  },
  {
    id: 197,
    topic: "grammar",
    de: "Ohne dich",
    ru: "Без тебя",
    grammar: "Ohne + Akkusativ.",
  },
  {
    id: 198,
    topic: "grammar",
    de: "Gegen uns",
    ru: "Против нас",
    grammar: "Gegen + Akkusativ.",
  },
  {
    id: 199,
    topic: "grammar",
    de: "Mit wem?",
    ru: "С кем?",
    grammar: "Вопрос Dativ (Mit + Wem).",
  },
  {
    id: 200,
    topic: "grammar",
    de: "Für wen?",
    ru: "Для кого?",
    grammar: "Вопрос Akkusativ (Für + Wen).",
  },
  // ==========================================
  // ТЕМА 14: ADJECTIVES & COLORS (Описания)
  // ==========================================
  {
    id: 201,
    topic: "adjectives",
    de: "Der Apfel ist rot",
    ru: "Яблоко красное",
    grammar: "Прилагательное (цвет).",
  },
  {
    id: 202,
    topic: "adjectives",
    de: "Der Himmel ist blau",
    ru: "Небо голубое",
    grammar: "Прилагательное (цвет).",
  },
  {
    id: 203,
    topic: "adjectives",
    de: "Das Gras ist grün",
    ru: "Трава зеленая",
    grammar: "Прилагательное (цвет).",
  },
  {
    id: 204,
    topic: "adjectives",
    de: "Der Schnee ist weiß",
    ru: "Снег белый",
    grammar: "Прилагательное (цвет).",
  },
  {
    id: 205,
    topic: "adjectives",
    de: "Die Nacht ist schwarz",
    ru: "Ночь черная",
    grammar: "Прилагательное (цвет).",
  },
  {
    id: 206,
    topic: "adjectives",
    de: "Die Sonne ist gelb",
    ru: "Солнце желтое",
    grammar: "Прилагательное (цвет).",
  },
  {
    id: 207,
    topic: "adjectives",
    de: "Das Auto ist schnell",
    ru: "Машина быстрая",
    grammar: "Прилагательное.",
  },
  {
    id: 208,
    topic: "adjectives",
    de: "Der Bus ist langsam",
    ru: "Автобус медленный",
    grammar: "Прилагательное.",
  },
  {
    id: 209,
    topic: "adjectives",
    de: "Die Musik ist laut",
    ru: "Музыка громкая",
    grammar: "Прилагательное.",
  },
  {
    id: 210,
    topic: "adjectives",
    de: "Sei bitte leise",
    ru: "Пожалуйста, потише",
    grammar: "Imperativ + Прилагательное.",
  },
  {
    id: 211,
    topic: "adjectives",
    de: "Das ist schwer",
    ru: "Это тяжело",
    grammar: "Прилагательное.",
  },
  {
    id: 212,
    topic: "adjectives",
    de: "Das ist leicht",
    ru: "Это легко",
    grammar: "Прилагательное.",
  },
  {
    id: 213,
    topic: "adjectives",
    de: "Die Wohnung ist teuer",
    ru: "Квартира дорогая",
    grammar: "Прилагательное.",
  },
  {
    id: 214,
    topic: "adjectives",
    de: "Das Buch ist interessant",
    ru: "Книга интересная",
    grammar: "Прилагательное.",
  },
  {
    id: 215,
    topic: "adjectives",
    de: "Der Film ist langweilig",
    ru: "Фильм скучный",
    grammar: "Прилагательное.",
  },
  {
    id: 216,
    topic: "adjectives",
    de: "Ich bin glücklich",
    ru: "Я счастлив",
    grammar: "Описние эмоций.",
  },
  {
    id: 217,
    topic: "adjectives",
    de: "Ich bin traurig",
    ru: "Мне грустно",
    grammar: "Описние эмоций.",
  },
  {
    id: 218,
    topic: "adjectives",
    de: "Das ist wichtig",
    ru: "Это важно",
    grammar: "Прилагательное.",
  },
  {
    id: 219,
    topic: "adjectives",
    de: "Das ist richtig",
    ru: "Это правильно",
    grammar: "Прилагательное.",
  },
  {
    id: 220,
    topic: "adjectives",
    de: "Das ist falsch",
    ru: "Это неправильно",
    grammar: "Прилагательное.",
  },

  // ==========================================
  // ТЕМА 15: BODY (Тело и Внешность)
  // ==========================================
  {
    id: 221,
    topic: "body",
    de: "Der Kopf",
    ru: "Голова",
    grammar: "Мужской род.",
  },
  {
    id: 222,
    topic: "body",
    de: "Die Hand",
    ru: "Рука (кисть)",
    grammar: "Женский род.",
  },
  {
    id: 223,
    topic: "body",
    de: "Der Arm",
    ru: "Рука (вся)",
    grammar: "Мужской род.",
  },
  {
    id: 224,
    topic: "body",
    de: "Das Bein",
    ru: "Нога",
    grammar: "Средний род.",
  },
  {
    id: 225,
    topic: "body",
    de: "Der Fuß",
    ru: "Ступня",
    grammar: "Мужской род.",
  },
  {
    id: 226,
    topic: "body",
    de: "Das Auge",
    ru: "Глаз",
    grammar: "Средний род.",
  },
  {
    id: 227,
    topic: "body",
    de: "Die Augen",
    ru: "Глаза",
    grammar: "Множественное число.",
  },
  {
    id: 228,
    topic: "body",
    de: "Der Bauch",
    ru: "Живот",
    grammar: "Мужской род.",
  },
  {
    id: 229,
    topic: "body",
    de: "Der Rücken",
    ru: "Спина",
    grammar: "Мужской род.",
  },
  {
    id: 230,
    topic: "body",
    de: "Der Mund",
    ru: "Рот",
    grammar: "Мужской род.",
  },
  {
    id: 231,
    topic: "body",
    de: "Die Nase",
    ru: "Нос",
    grammar: "Женский род.",
  },
  { id: 232, topic: "body", de: "Die Haare", ru: "Волосы", grammar: "Plural." },
  {
    id: 233,
    topic: "body",
    de: "Er hat blaue Augen",
    ru: "У него голубые глаза",
    grammar: "Akkusativ Plural.",
  },
  {
    id: 234,
    topic: "body",
    de: "Sie hat lange Haare",
    ru: "У нее длинные волосы",
    grammar: "Akkusativ Plural.",
  },
  {
    id: 235,
    topic: "body",
    de: "Mein Herz",
    ru: "Мое сердце",
    grammar: "Средний род.",
  },

  // ==========================================
  // ТЕМА 16: CLOTHES (Одежда - Детали)
  // ==========================================
  {
    id: 236,
    topic: "clothes",
    de: "Ich trage eine Hose",
    ru: "Я ношу брюки",
    grammar: "Hose (жен. род) + Akkusativ.",
  },
  {
    id: 237,
    topic: "clothes",
    de: "Das T-Shirt",
    ru: "Футболка",
    grammar: "Средний род.",
  },
  {
    id: 238,
    topic: "clothes",
    de: "Der Pullover",
    ru: "Свитер",
    grammar: "Мужской род.",
  },
  {
    id: 239,
    topic: "clothes",
    de: "Die Jacke",
    ru: "Куртка",
    grammar: "Женский род.",
  },
  {
    id: 240,
    topic: "clothes",
    de: "Das Kleid",
    ru: "Платье",
    grammar: "Средний род.",
  },
  {
    id: 241,
    topic: "clothes",
    de: "Der Rock",
    ru: "Юбка",
    grammar: "Мужской род.",
  },
  {
    id: 242,
    topic: "clothes",
    de: "Die Schuhe",
    ru: "Обувь",
    grammar: "Plural.",
  },
  {
    id: 243,
    topic: "clothes",
    de: "Ich brauche neue Schuhe",
    ru: "Мне нужна новая обувь",
    grammar: "Akkusativ Plural.",
  },
  {
    id: 244,
    topic: "clothes",
    de: "Die Mütze",
    ru: "Шапка",
    grammar: "Женский род.",
  },
  {
    id: 245,
    topic: "clothes",
    de: "Der Schal",
    ru: "Шарф",
    grammar: "Мужской род.",
  },
  {
    id: 246,
    topic: "clothes",
    de: "Zieh dich an",
    ru: "Одевайся",
    grammar: "Imperativ (Reflexiv).",
  },
  {
    id: 247,
    topic: "clothes",
    de: "Zieh die Jacke aus",
    ru: "Сними куртку",
    grammar: "Ausziehen (снимать).",
  },
  {
    id: 248,
    topic: "clothes",
    de: "Das steht dir gut",
    ru: "Это тебе идет",
    grammar: "Dativ (Dir).",
  },
  {
    id: 249,
    topic: "clothes",
    de: "Die Brille",
    ru: "Очки",
    grammar: "Женский род (ед.ч. в немецком).",
  },
  {
    id: 250,
    topic: "clothes",
    de: "Die Tasche",
    ru: "Сумка",
    grammar: "Женский род.",
  },

  // ==========================================
  // ТЕМА 17: SCHOOL (Школа и Учеба)
  // ==========================================
  {
    id: 251,
    topic: "school",
    de: "Die Schule",
    ru: "Школа",
    grammar: "Женский род.",
  },
  {
    id: 252,
    topic: "school",
    de: "Der Lehrer",
    ru: "Учитель",
    grammar: "Мужской род.",
  },
  {
    id: 253,
    topic: "school",
    de: "Die Schülerin",
    ru: "Ученица",
    grammar: "Женский род (-in).",
  },
  {
    id: 254,
    topic: "school",
    de: "Das Buch",
    ru: "Книга",
    grammar: "Средний род.",
  },
  {
    id: 255,
    topic: "school",
    de: "Das Heft",
    ru: "Тетрадь",
    grammar: "Средний род.",
  },
  {
    id: 256,
    topic: "school",
    de: "Der Stift",
    ru: "Ручка/Карандаш",
    grammar: "Мужской род.",
  },
  {
    id: 257,
    topic: "school",
    de: "Ich lerne Deutsch",
    ru: "Я учу немецкий",
    grammar: "Глагол lernen.",
  },
  {
    id: 258,
    topic: "school",
    de: "Ich mache Hausaufgaben",
    ru: "Я делаю домашнее задание",
    grammar: "Plural.",
  },
  {
    id: 259,
    topic: "school",
    de: "Die Frage",
    ru: "Вопрос",
    grammar: "Женский род.",
  },
  {
    id: 260,
    topic: "school",
    de: "Die Antwort",
    ru: "Ответ",
    grammar: "Женский род.",
  },
  {
    id: 261,
    topic: "school",
    de: "Ich habe eine Frage",
    ru: "У меня есть вопрос",
    grammar: "Akkusativ.",
  },
  {
    id: 262,
    topic: "school",
    de: "Der Kurs",
    ru: "Курс",
    grammar: "Мужской род.",
  },
  {
    id: 263,
    topic: "school",
    de: "Die Prüfung",
    ru: "Экзамен",
    grammar: "Женский род.",
  },
  {
    id: 264,
    topic: "school",
    de: "Viel Erfolg!",
    ru: "Успехов!",
    grammar: "Пожелание перед экзаменом.",
  },
  {
    id: 265,
    topic: "school",
    de: "Das ist schwer",
    ru: "Это трудно",
    grammar: "Прилагательное.",
  },

  // ==========================================
  // ТЕМА 18: DAILY ROUTINE (Распорядок дня - Verben)
  // ==========================================
  {
    id: 266,
    topic: "routine",
    de: "Ich stehe auf",
    ru: "Я встаю",
    grammar: "Aufstehen (отделяемая приставка).",
  },
  {
    id: 267,
    topic: "routine",
    de: "Ich putze mir die Zähne",
    ru: "Я чищу зубы",
    grammar: "Putzen.",
  },
  {
    id: 268,
    topic: "routine",
    de: "Ich dusche",
    ru: "Я принимаю душ",
    grammar: "Глагол duschen.",
  },
  {
    id: 269,
    topic: "routine",
    de: "Ich frühstücke",
    ru: "Я завтракаю",
    grammar: "Глагол frühstücken.",
  },
  {
    id: 270,
    topic: "routine",
    de: "Ich gehe zur Arbeit",
    ru: "Я иду на работу",
    grammar: "Zu der = Zur (Dativ).",
  },
  {
    id: 271,
    topic: "routine",
    de: "Ich fahre nach Hause",
    ru: "Я еду домой",
    grammar: "Nach Hause (домой).",
  },
  {
    id: 272,
    topic: "routine",
    de: "Ich kaufe ein",
    ru: "Я закупаюсь",
    grammar: "Einkaufen (отделяемая приставка).",
  },
  {
    id: 273,
    topic: "routine",
    de: "Ich koche",
    ru: "Я готовлю",
    grammar: "Kochen.",
  },
  {
    id: 274,
    topic: "routine",
    de: "Ich räume auf",
    ru: "Я убираюсь",
    grammar: "Aufräumen (отделяемая приставка).",
  },
  {
    id: 275,
    topic: "routine",
    de: "Ich sehe fern",
    ru: "Я смотрю ТВ",
    grammar: "Fernsehen (сильный глагол + приставка).",
  },
  {
    id: 276,
    topic: "routine",
    de: "Ich rufe an",
    ru: "Я звоню",
    grammar: "Anrufen (отделяемая приставка).",
  },
  {
    id: 277,
    topic: "routine",
    de: "Ich gehe schlafen",
    ru: "Я иду спать",
    grammar: "Gehen + Infinitiv.",
  },
  {
    id: 278,
    topic: "routine",
    de: "Ich schlafe ein",
    ru: "Я засыпаю",
    grammar: "Einschlafen (отделяемая).",
  },
  {
    id: 279,
    topic: "routine",
    de: "Der Alltag",
    ru: "Будни / Быт",
    grammar: "Существительное.",
  },
  {
    id: 280,
    topic: "routine",
    de: "Jeden Morgen",
    ru: "Каждое утро",
    grammar: "Akkusativ времени.",
  },

  // ==========================================
  // ТЕМА 19: PREPOSITIONS (Предлоги - Тренажер)
  // ==========================================
  {
    id: 281,
    topic: "grammar",
    de: "Der Ball ist unter dem Tisch",
    ru: "Мяч под столом",
    grammar: "Unter + Dativ (Где?).",
  },
  {
    id: 282,
    topic: "grammar",
    de: "Der Ball ist auf dem Tisch",
    ru: "Мяч на столе",
    grammar: "Auf + Dativ (Где?).",
  },
  {
    id: 283,
    topic: "grammar",
    de: "Ich gehe in die Schule",
    ru: "Я иду в школу",
    grammar: "In + Akkusativ (Куда?).",
  },
  {
    id: 284,
    topic: "grammar",
    de: "Ich bin in der Schule",
    ru: "Я в школе",
    grammar: "In + Dativ (Где?).",
  },
  {
    id: 285,
    topic: "grammar",
    de: "Neben mir",
    ru: "Рядом со мной",
    grammar: "Neben + Dativ.",
  },
  {
    id: 286,
    topic: "grammar",
    de: "Zwischen den Stühlen",
    ru: "Между стульями",
    grammar: "Zwischen + Dativ Plural.",
  },
  {
    id: 287,
    topic: "grammar",
    de: "Hinter dem Haus",
    ru: "За домом",
    grammar: "Hinter + Dativ.",
  },
  {
    id: 288,
    topic: "grammar",
    de: "Vor dem Essen",
    ru: "Перед едой",
    grammar: "Vor + Dativ.",
  },
  {
    id: 289,
    topic: "grammar",
    de: "Über dem Sofa",
    ru: "Над диваном",
    grammar: "Über + Dativ.",
  },
  {
    id: 290,
    topic: "grammar",
    de: "Ohne Zucker",
    ru: "Без сахара",
    grammar: "Ohne + Akkusativ.",
  },
  {
    id: 291,
    topic: "grammar",
    de: "Für dich",
    ru: "Для тебя",
    grammar: "Für + Akkusativ.",
  },
  {
    id: 292,
    topic: "grammar",
    de: "Gegen mich",
    ru: "Против меня",
    grammar: "Gegen + Akkusativ.",
  },
  {
    id: 293,
    topic: "grammar",
    de: "Um 8 Uhr",
    ru: "В 8 часов",
    grammar: "Um (время).",
  },
  {
    id: 294,
    topic: "grammar",
    de: "Bis später",
    ru: "До скорого",
    grammar: "Bis (до).",
  },
  {
    id: 295,
    topic: "grammar",
    de: "Von mir",
    ru: "От меня",
    grammar: "Von + Dativ.",
  },

  // ==========================================
  // ТЕМА 20: NATURE & ANIMALS (Природа)
  // ==========================================
  {
    id: 296,
    topic: "nature",
    de: "Der Hund",
    ru: "Собака",
    grammar: "Мужской род.",
  },
  {
    id: 297,
    topic: "nature",
    de: "Die Katze",
    ru: "Кошка",
    grammar: "Женский род.",
  },
  {
    id: 298,
    topic: "nature",
    de: "Das Tier",
    ru: "Животное",
    grammar: "Средний род.",
  },
  {
    id: 299,
    topic: "nature",
    de: "Der Baum",
    ru: "Дерево",
    grammar: "Мужской род.",
  },
  {
    id: 300,
    topic: "nature",
    de: "Die Blume",
    ru: "Цветок",
    grammar: "Женский род.",
  },
  {
    id: 301,
    topic: "nature",
    de: "Der Wald",
    ru: "Лес",
    grammar: "Мужской род.",
  },
  {
    id: 302,
    topic: "nature",
    de: "Der Fluss",
    ru: "Река",
    grammar: "Мужской род.",
  },
  {
    id: 303,
    topic: "nature",
    de: "Das Meer",
    ru: "Море",
    grammar: "Средний род.",
  },
  {
    id: 304,
    topic: "nature",
    de: "Der Berg",
    ru: "Гора",
    grammar: "Мужской род.",
  },
  {
    id: 305,
    topic: "nature",
    de: "Der Vogel",
    ru: "Птица",
    grammar: "Мужской род.",
  },
  {
    id: 306,
    topic: "nature",
    de: "Draußen",
    ru: "Снаружи / На улице",
    grammar: "Наречие.",
  },
  {
    id: 307,
    topic: "nature",
    de: "Die Luft",
    ru: "Воздух",
    grammar: "Женский род.",
  },
  {
    id: 308,
    topic: "nature",
    de: "Der Stern",
    ru: "Звезда",
    grammar: "Мужской род.",
  },
  {
    id: 309,
    topic: "nature",
    de: "Der Mond",
    ru: "Луна",
    grammar: "Мужской род.",
  },
  {
    id: 310,
    topic: "nature",
    de: "Spazieren gehen",
    ru: "Идти гулять",
    grammar: "Глагол.",
  },

  // ==========================================
  // ТЕМА 21: NUMBERS & MONEY (Числа)
  // ==========================================
  {
    id: 311,
    topic: "shopping",
    de: "Eins, zwei, drei",
    ru: "1, 2, 3",
    grammar: "Числа.",
  },
  {
    id: 312,
    topic: "shopping",
    de: "Zehn, zwanzig, dreißig",
    ru: "10, 20, 30",
    grammar: "Десятки.",
  },
  { id: 313, topic: "shopping", de: "Hundert", ru: "100", grammar: "Сотня." },
  { id: 314, topic: "shopping", de: "Tausend", ru: "1000", grammar: "Тысяча." },
  {
    id: 315,
    topic: "shopping",
    de: "Der Euro",
    ru: "Евро",
    grammar: "Валюта.",
  },
  {
    id: 316,
    topic: "shopping",
    de: "Der Cent",
    ru: "Цент",
    grammar: "Мелочь.",
  },
  {
    id: 317,
    topic: "shopping",
    de: "Das Geld",
    ru: "Деньги",
    grammar: "Средний род (всегда ед.ч.).",
  },
  {
    id: 318,
    topic: "shopping",
    de: "Ich habe kein Geld",
    ru: "У меня нет денег",
    grammar: "Kein + Сущ.",
  },
  {
    id: 319,
    topic: "shopping",
    de: "Erste",
    ru: "Первый",
    grammar: "Порядковое числительное.",
  },
  {
    id: 320,
    topic: "shopping",
    de: "Zweite",
    ru: "Второй",
    grammar: "Порядковое числительное.",
  },

  // ==========================================
  // ТЕМА 22: TRAVEL (Путешествия - Расширенная)
  // ==========================================
  {
    id: 321,
    topic: "city",
    de: "Der Urlaub",
    ru: "Отпуск",
    grammar: "Мужской род.",
  },
  {
    id: 322,
    topic: "city",
    de: "Die Reise",
    ru: "Путешествие",
    grammar: "Женский род.",
  },
  {
    id: 323,
    topic: "city",
    de: "Der Koffer",
    ru: "Чемодан",
    grammar: "Мужской род.",
  },
  {
    id: 324,
    topic: "city",
    de: "Das Gepäck",
    ru: "Багаж",
    grammar: "Средний род.",
  },
  {
    id: 325,
    topic: "city",
    de: "Der Pass",
    ru: "Паспорт",
    grammar: "Мужской род.",
  },
  {
    id: 326,
    topic: "city",
    de: "Das Flugzeug",
    ru: "Самолет",
    grammar: "Средний род.",
  },
  {
    id: 327,
    topic: "city",
    de: "Abfahren",
    ru: "Отъезжать",
    grammar: "Глагол.",
  },
  {
    id: 328,
    topic: "city",
    de: "Ankommen",
    ru: "Прибывать",
    grammar: "Глагол.",
  },
  {
    id: 329,
    topic: "city",
    de: "Das Gleis",
    ru: "Платформа / Путь",
    grammar: "На вокзале.",
  },
  {
    id: 330,
    topic: "city",
    de: "Ein Ticket buchen",
    ru: "Бронировать билет",
    grammar: "Фраза.",
  },
  {
    id: 331,
    topic: "city",
    de: "Die Stadt",
    ru: "Город",
    grammar: "Женский род.",
  },
  {
    id: 332,
    topic: "city",
    de: "Das Land",
    ru: "Страна / Деревня",
    grammar: "Средний род.",
  },
  {
    id: 333,
    topic: "city",
    de: "Die Karte",
    ru: "Карта",
    grammar: "Женский род.",
  },
  {
    id: 334,
    topic: "city",
    de: "Ich möchte nach Berlin",
    ru: "Я хочу в Берлин",
    grammar: "Nach + Город.",
  },
  {
    id: 335,
    topic: "city",
    de: "Gute Fahrt!",
    ru: "Счастливого пути!",
    grammar: "Пожелание.",
  },

  // ==========================================
  // ТЕМА 23: QUESTION WORDS (Вопросительные слова - W-Fragen)
  // ==========================================
  {
    id: 336,
    topic: "grammar",
    de: "Wer ist das?",
    ru: "Кто это?",
    grammar: "Wer - Кто.",
  },
  {
    id: 337,
    topic: "grammar",
    de: "Was ist das?",
    ru: "Что это?",
    grammar: "Was - Что.",
  },
  {
    id: 338,
    topic: "grammar",
    de: "Wo wohnst du?",
    ru: "Где ты живешь?",
    grammar: "Wo - Где.",
  },
  {
    id: 339,
    topic: "grammar",
    de: "Wohin gehst du?",
    ru: "Куда ты идешь?",
    grammar: "Wohin - Куда.",
  },
  {
    id: 340,
    topic: "grammar",
    de: "Woher kommst du?",
    ru: "Откуда ты?",
    grammar: "Woher - Откуда.",
  },
  {
    id: 341,
    topic: "grammar",
    de: "Wann kommst du?",
    ru: "Когда ты придешь?",
    grammar: "Wann - Когда.",
  },
  {
    id: 342,
    topic: "grammar",
    de: "Wie heißt du?",
    ru: "Как тебя зовут?",
    grammar: "Wie - Как.",
  },
  {
    id: 343,
    topic: "grammar",
    de: "Warum machst du das?",
    ru: "Почему ты это делаешь?",
    grammar: "Warum - Почему.",
  },
  {
    id: 344,
    topic: "grammar",
    de: "Welche Farbe?",
    ru: "Какой цвет?",
    grammar: "Welche - Какой/Который.",
  },
  {
    id: 345,
    topic: "grammar",
    de: "Wie viel kostet das?",
    ru: "Сколько это стоит?",
    grammar: "Wie viel - Сколько.",
  },

  // ==========================================
  // ТЕМА 24: VERBS (Важные глаголы действия)
  // ==========================================
  {
    id: 346,
    topic: "grammar",
    de: "Ich gebe dir das Buch",
    ru: "Я даю тебе книгу",
    grammar: "Geben (давать) + Dativ + Akk.",
  },
  {
    id: 347,
    topic: "grammar",
    de: "Ich nehme den Bus",
    ru: "Я сажусь на автобус (беру)",
    grammar: "Nehmen (брать).",
  },
  {
    id: 348,
    topic: "grammar",
    de: "Ich finde den Schlüssel",
    ru: "Я нахожу ключ",
    grammar: "Finden (находить).",
  },
  {
    id: 349,
    topic: "grammar",
    de: "Ich suche den Schlüssel",
    ru: "Я ищу ключ",
    grammar: "Suchen (искать).",
  },
  {
    id: 350,
    topic: "grammar",
    de: "Ich warte auf dich",
    ru: "Я жду тебя",
    grammar: "Warten auf + Akkusativ.",
  },
  {
    id: 351,
    topic: "grammar",
    de: "Ich denke an dich",
    ru: "Я думаю о тебе",
    grammar: "Denken an + Akkusativ.",
  },
  {
    id: 352,
    topic: "grammar",
    de: "Ich bringe das Essen",
    ru: "Я приношу еду",
    grammar: "Bringen (приносить).",
  },
  {
    id: 353,
    topic: "grammar",
    de: "Er schenkt mir Blumen",
    ru: "Он дарит мне цветы",
    grammar: "Schenken (дарить).",
  },
  {
    id: 354,
    topic: "grammar",
    de: "Wir spielen Fußball",
    ru: "Мы играем в футбол",
    grammar: "Spielen (играть).",
  },
  {
    id: 355,
    topic: "grammar",
    de: "Sie singt gut",
    ru: "Она поет хорошо",
    grammar: "Singen (петь).",
  },
  {
    id: 356,
    topic: "grammar",
    de: "Er tanzt gern",
    ru: "Он любит танцевать",
    grammar: "Tanzen + gern.",
  },
  {
    id: 357,
    topic: "grammar",
    de: "Ich schwimme im Meer",
    ru: "Я плаваю в море",
    grammar: "Schwimmen.",
  },
  {
    id: 358,
    topic: "grammar",
    de: "Ich laufe schnell",
    ru: "Я бегу быстро",
    grammar: "Laufen (сильный глагол).",
  },
  {
    id: 359,
    topic: "grammar",
    de: "Wir sitzen hier",
    ru: "Мы сидим здесь",
    grammar: "Sitzen.",
  },
  {
    id: 360,
    topic: "grammar",
    de: "Das Buch liegt hier",
    ru: "Книга лежит здесь",
    grammar: "Liegen.",
  },

  // ==========================================
  // ТЕМА 25: STRUCTURE & CONJUNCTIONS (Союзы)
  // ==========================================
  {
    id: 361,
    topic: "grammar",
    de: "Ich bin müde, denn ich habe gearbeitet",
    ru: "Я устал, так как работал",
    grammar: "Denn (не меняет порядок слов).",
  },
  {
    id: 362,
    topic: "grammar",
    de: "Ich komme, aber ich habe keine Zeit",
    ru: "Я приду, но у меня нет времени",
    grammar: "Aber (но).",
  },
  {
    id: 363,
    topic: "grammar",
    de: "Kaffee oder Tee?",
    ru: "Кофе или чай?",
    grammar: "Oder (или).",
  },
  {
    id: 364,
    topic: "grammar",
    de: "Brot und Wasser",
    ru: "Хлеб и вода",
    grammar: "Und (и).",
  },
  {
    id: 365,
    topic: "grammar",
    de: "Zuerst essen wir",
    ru: "Сначала мы едим",
    grammar: "Zuerst (сначала).",
  },
  {
    id: 366,
    topic: "grammar",
    de: "Dann gehen wir",
    ru: "Потом мы идем",
    grammar: "Dann (потом) - меняет порядок слов.",
  },
  {
    id: 367,
    topic: "grammar",
    de: "Deshalb lerne ich Deutsch",
    ru: "Поэтому я учу немецкий",
    grammar: "Deshalb (поэтому).",
  },
  {
    id: 368,
    topic: "grammar",
    de: "Ich hoffe, dass du kommst",
    ru: "Надеюсь, что ты придешь",
    grammar: "Dass (глагол в конец).",
  },
  {
    id: 369,
    topic: "grammar",
    de: "Wenn ich Zeit habe",
    ru: "Если у меня будет время",
    grammar: "Wenn (если/когда) - глагол в конец.",
  },
  { id: 370, topic: "grammar", de: "Auch", ru: "Тоже", grammar: "Наречие." },

  // ==========================================
  // ТЕМА 26: USEFUL PHRASES (Разное полезное)
  // ==========================================
  {
    id: 371,
    topic: "communication",
    de: "Das macht nichts",
    ru: "Ничего страшного",
    grammar: "Устойчивая фраза.",
  },
  {
    id: 372,
    topic: "communication",
    de: "Wie bitte?",
    ru: "Что простите?",
    grammar: "Если не расслышали.",
  },
  {
    id: 373,
    topic: "communication",
    de: "Einen Moment bitte",
    ru: "Один момент",
    grammar: "Просьба подождать.",
  },
  {
    id: 374,
    topic: "communication",
    de: "Das geht nicht",
    ru: "Так не пойдет / Не получится",
    grammar: "Отказ.",
  },
  {
    id: 375,
    topic: "communication",
    de: "Ich habe Recht",
    ru: "Я прав",
    grammar: "Recht haben.",
  },
  {
    id: 376,
    topic: "communication",
    de: "Du hast Recht",
    ru: "Ты прав",
    grammar: "Recht haben.",
  },
  {
    id: 377,
    topic: "communication",
    de: "Das ist mir egal",
    ru: "Мне всё равно",
    grammar: "Dativ (Mir).",
  },
  {
    id: 378,
    topic: "communication",
    de: "Keine Panik",
    ru: "Без паники",
    grammar: "Призыв.",
  },
  {
    id: 379,
    topic: "communication",
    de: "Achtung!",
    ru: "Внимание!",
    grammar: "Предупреждение.",
  },
  {
    id: 380,
    topic: "communication",
    de: "Vorsicht!",
    ru: "Осторожно!",
    grammar: "Предупреждение.",
  },
  {
    id: 381,
    topic: "communication",
    de: "Ich bin fertig",
    ru: "Я готов / Я закончил",
    grammar: "Fertig.",
  },
  {
    id: 382,
    topic: "communication",
    de: "Bist du fertig?",
    ru: "Ты закончил?",
    grammar: "Вопрос.",
  },
  {
    id: 383,
    topic: "communication",
    de: "Los geht's!",
    ru: "Погнали! / Начали!",
    grammar: "Старт.",
  },
  {
    id: 384,
    topic: "communication",
    de: "Schade",
    ru: "Жаль",
    grammar: "Выражение эмоции.",
  },
  {
    id: 385,
    topic: "communication",
    de: "Toll!",
    ru: "Здорово!",
    grammar: "Похвала.",
  },
  {
    id: 386,
    topic: "communication",
    de: "Super!",
    ru: "Супер!",
    grammar: "Похвала.",
  },
  {
    id: 387,
    topic: "communication",
    de: "Genug",
    ru: "Достаточно",
    grammar: "Наречие.",
  },
  {
    id: 388,
    topic: "communication",
    de: "Mehr",
    ru: "Больше",
    grammar: "Сравнение.",
  },
  {
    id: 389,
    topic: "communication",
    de: "Weniger",
    ru: "Меньше",
    grammar: "Сравнение.",
  },
  {
    id: 390,
    topic: "communication",
    de: "Vielleicht später",
    ru: "Может быть позже",
    grammar: "Отказ.",
  },
  {
    id: 391,
    topic: "communication",
    de: "Ich habe keine Lust",
    ru: "У меня нет желания",
    grammar: "Keine Lust.",
  },
  {
    id: 392,
    topic: "communication",
    de: "Hast du Zeit?",
    ru: "У тебя есть время?",
    grammar: "Вопрос.",
  },
  {
    id: 393,
    topic: "communication",
    de: "Ich bin beschäftigt",
    ru: "Я занят",
    grammar: "Beschäftigt.",
  },
  {
    id: 394,
    topic: "communication",
    de: "Ruf mich an",
    ru: "Позвони мне",
    grammar: "Imperativ.",
  },
  {
    id: 395,
    topic: "communication",
    de: "Schreib mir",
    ru: "Напиши мне",
    grammar: "Imperativ.",
  },
  {
    id: 396,
    topic: "communication",
    de: "Vergiss das nicht",
    ru: "Не забудь это",
    grammar: "Vergessen.",
  },
  {
    id: 397,
    topic: "communication",
    de: "Ich erinnere mich",
    ru: "Я помню",
    grammar: "Reflexiv.",
  },
  {
    id: 398,
    topic: "communication",
    de: "Herzlichen Glückwunsch",
    ru: "Поздравляю",
    grammar: "Праздник.",
  },
  {
    id: 399,
    topic: "communication",
    de: "Alles Gute",
    ru: "Всего хорошего",
    grammar: "Пожелание.",
  },
  {
    id: 400,
    topic: "communication",
    de: "Ende",
    ru: "Конец",
    grammar: "Конец списка.",
  },
];
